// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4uQxPndRxjx1DrUYZEHr6b8iCf_41CEI',
    appId: '1:943366099304:web:7a3930875d06ca0c26c6dd',
    messagingSenderId: '943366099304',
    projectId: 'flutter-push-notif-83196',
    authDomain: 'flutter-push-notif-83196.firebaseapp.com',
    storageBucket: 'flutter-push-notif-83196.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMj1bUniiI78OIzZAz1E-zexUCRfpJ6ZY',
    appId: '1:943366099304:android:c5bb5b05b5a8e5e426c6dd',
    messagingSenderId: '943366099304',
    projectId: 'flutter-push-notif-83196',
    storageBucket: 'flutter-push-notif-83196.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNdfaRL0y6kJbp_MMsX372e6bhCsOxLgo',
    appId: '1:943366099304:ios:a12ab2a33e49b95326c6dd',
    messagingSenderId: '943366099304',
    projectId: 'flutter-push-notif-83196',
    storageBucket: 'flutter-push-notif-83196.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNdfaRL0y6kJbp_MMsX372e6bhCsOxLgo',
    appId: '1:943366099304:ios:a12ab2a33e49b95326c6dd',
    messagingSenderId: '943366099304',
    projectId: 'flutter-push-notif-83196',
    storageBucket: 'flutter-push-notif-83196.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4uQxPndRxjx1DrUYZEHr6b8iCf_41CEI',
    appId: '1:943366099304:web:b450e247829a557926c6dd',
    messagingSenderId: '943366099304',
    projectId: 'flutter-push-notif-83196',
    authDomain: 'flutter-push-notif-83196.firebaseapp.com',
    storageBucket: 'flutter-push-notif-83196.appspot.com',
  );
}
